chat/urls.py
# chat/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("<int:group_pk>/", views.group_chat, name="group_chat"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
import custom_ckeditor.views

from schedules.urls import user_schedule_router 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('accounts/', include('accounts.urls')),
    path('diaries/', include('diaries.urls')),
    path('groups/', include('groups.urls')),
    path('schedules/', include('schedules.urls')),
    path("chat/", include("chat.urls")),
    path("ckeditor5/image_upload/", custom_ckeditor.views.upload_file, name="ck_editor_5_upload_file"),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('accounts/', include('allauth.urls')),
    path('schedules/', include(user_schedule_router.urls)),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diaries/urls.py
from django.urls import path
from . import views

app_name = 'diaries'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:diary_pk>/', views.detail, name='detail'),
    path('<int:diary_pk>/update/', views.update, name='update'),
    path('<int:diary_pk>/delete/', views.delete, name='delete'),
    path('<int:group_pk>/<int:diary_pk>/', views.group_detail, name='group_detail'),
    path('<int:group_pk>/<int:diary_pk>/share/', views.share, name='share'),
    path('<int:group_pk>/<int:diary_pk>/unshare/', views.unshare, name='unshare'),
    path('<int:group_pk>/<int:diary_pk>/emotes/<int:emotion>/', views.emotes, name='emotes'),
    path('<int:group_pk>/<int:diary_pk>/comment_create/', views.comment_create, name='comment_create'),
    path('<int:group_pk>/<int:diary_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
    path('<int:group_pk>/<int:diary_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:group_pk>/<int:diary_pk>/comments/<int:comment_pk>/like/', views.comment_like, name='comment_like'),
]

groups/urls.py
from django.urls import path, include
from schedules.urls import group_schedule_router
from . import views

app_name = 'groups'
urlpatterns = [
    path('', views.index, name='index'),
    # 그룹
    path('create/', views.group_create, name='group_create'),
    path('<int:group_pk>/join/', views.group_join, name='group_join'),
    path('<int:group_pk>/', views.group_detail, name='group_detail'),
    path('<int:group_pk>/setting/', views.group_setting, name='group_setting'),
    path('<int:group_pk>/update/', views.group_update, name='group_update'),
    path('<int:group_pk>/delete/', views.group_delete, name='group_delete'),
    path('<int:group_pk>/password_update/', views.password_update, name='password_update'),
    path('<int:group_pk>/members/withdraw/', views.member_withdraw, name='member_withdraw'), # 멤버 탈퇴(본인이)
    path('<int:group_pk>/members/<str:username>/delete/', views.member_delete, name='member_delete'), # 멤버 삭제(방장 권한)
    path('<int:group_pk>/chief/<str:username>/change/', views.chief_change, name='chief_change'), # 방장 위임
    # 게시글
    path('<int:group_pk>/posts/create/', views.post_create, name='post_create'),
    path('<int:group_pk>/posts/<int:post_pk>/', views.post_detail, name='post_detail'),
    path('<int:group_pk>/posts/<int:post_pk>/update/', views.post_update, name='post_update'),
    path('<int:group_pk>/posts/<int:post_pk>/delete/', views.post_delete, name='post_delete'),
    path('<int:group_pk>/posts/<int:post_pk>/emotes/<int:emotion>/', views.emote, name='emote'),
    path('<int:group_pk>/posts/<int:post_pk>/comment/create/', views.comment_create, name='comment_create'),
    path('<int:group_pk>/posts/<int:post_pk>/comment/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
    path('<int:group_pk>/posts/<int:post_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:group_pk>/posts/<int:post_pk>/comments/<int:comment_pk>/like/', views.comment_like, name='comment_like'),
    path('<int:group_pk>/posts/<int:post_pk>/notice/', views.notice_post, name='notice_post'),
    # 투표
    path('<int:group_pk>/votes/create/', views.vote_create, name='vote_create'),
    path('votes/<int:vote_pk>/', views.get_vote, name='get_vote'),
    path('<int:group_pk>/votes/<int:vote_pk>/throw/', views.throw_vote, name='throw_vote'),
    path('<int:group_pk>/votes/<int:vote_pk>/add_option/', views.add_option, name='add_option'),
    path('<int:group_pk>/votes/<int:vote_pk>/update/', views.vote_update, name='vote_update'),
    path('<int:group_pk>/votes/<int:vote_pk>/delete/', views.vote_delete, name='vote_delete'),
    path('<int:group_pk>/votes/<int:vote_pk>/notice/', views.notice_vote, name='notice_vote'),
    path('votes/<int:vote_pk>/hits/', views.vote_hits, name='vote_hits'),
    path('search/', views.group_search, name='group_search'),
    path('<int:group_pk>/calendars/', include(group_schedule_router.urls)),
]

groups/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from datetime import datetime, timedelta
from django.utils import timezone
from django.contrib.contenttypes import fields


class GroupManager(models.Manager):
    def create(self, **kwargs):
        group = super().create(**kwargs)
        group._calendar.create()
        return group


class Group(models.Model):
    chief = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    group_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='user_groups')
    name = models.CharField(max_length=100)
    password = models.CharField(max_length=128)
    _calendar = fields.GenericRelation('schedules.Calendar', object_id_field='owner_object_id', content_type_field='owner_content_type', related_query_name='owner_group')

    def group_image_path(instance, filename):
        return f'groups/{instance.name}_{instance.pk}/{filename}'
    
    thumbnail = ProcessedImageField(upload_to=group_image_path, blank=True,
                                    processors=[ResizeToFill(500,500)],
                                    format='JPEG',
                                    options={'quality': 100})
    intro = models.CharField(max_length=500)
    exp = models.PositiveIntegerField()
    level = models.PositiveIntegerField()
    # 기준 = 경험치/(그룹인원**0.5)
    # lv.1 : 새싹 단계, 기준 < 10       
    # lv.2 : 풀 단계, 기준 < 30          lv.7 : 판다 단계, 기준 < 280
    # lv.3 : 나무 단계, 기준 < 60        lv.8 : 레서판다 단계, 기준 < 360
    # lv.4 : 개화 단계, 기준 < 100       lv.9 : 유니콘 단계, 기준 < 450
    # lv.5 : 열매 단계, 기준 < 150       lv.10 : 뿔 달린 유니콘 단계, 기준 < 550
    # lv.6 : 반달곰 단계, 기준 < 210     lv.11 : 날개 달린 유니콘 단계, 기준 < 660

    created_at = models.DateTimeField(auto_now_add=True)

    objects = GroupManager()

    def __str__(self):
        return self.name
    
    @property
    def calendar(self):
         return self._calendar.all()[0]


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    # schedule = models.ForeignKey('schedules.GroupSchedule', on_delete=models.CASCADE, blank=True)
    hits = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='post_views')
    emote_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='emote_posts', through='PostEmote')
    title = models.CharField(max_length=200)
    content = models.TextField()
    is_notice = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    def get_model_name(self):
        return self._meta.model_name

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.created_at
        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(time.seconds // 60) + '분 전'
        elif time < timedelta(days=1):
            return str(time.seconds // 3600) + '시간 전'
        elif time < timedelta(weeks=1):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return self.created_at.strftime('%Y-%m-%d')
    

class PostImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def post_image_path(instance, filename):
        now = instance.post.created_at
        return f'groups/{instance.post.group.name}_{instance.post.group.pk}/' + now.strftime('%Y/%m/%d') + f'/{filename}'
    
    image = ProcessedImageField(upload_to=post_image_path, blank=True,
                                processors=[ResizeToFill(500,500)],
                                format='JPEG',
                                options={'quality': 100})


class PostEmote(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    emotion = models.PositiveIntegerField()
    # 1:👍 2:🥰 3:🤣 4:😲 5:😭 6:🥳


class PostComment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_post_comments')
    content = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.created_at
        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(time.seconds // 60) + '분 전'
        elif time < timedelta(days=1):
            return str(time.seconds // 3600) + '시간 전'
        elif time < timedelta(weeks=1):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return self.created_at.strftime('%Y-%m-%d')


class Vote(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    hits = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='vote_views')
    title = models.CharField(max_length=100)
    deadline = models.DateTimeField()
    is_notice = models.BooleanField()
    is_overlap = models.BooleanField()
    is_annony = models.BooleanField()
    is_addible = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    def get_model_name(self):
        return self._meta.model_name

    def d_day(self):
        time = self.deadline - datetime.now(tz=timezone.utc)
        if time < timedelta(seconds=1):
            return '투표 마감'
        elif time < timedelta(minutes=1):
            return '곧 마감'
        elif time < timedelta(hours=1):
            return str(time.seconds // 60) + '분 후 마감'
        elif time < timedelta(days=1):
            return str(time.seconds // 3600) + '시간 후 마감'
        else:
            return 'D-' + str(time.days)
    
    def is_end(self):
        if datetime.now(tz=timezone.utc) > self.deadline:
            return True
        else:
            return False

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.created_at
        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(time.seconds // 60) + '분 전'
        elif time < timedelta(days=1):
            return str(time.seconds // 3600) + '시간 전'
        elif time < timedelta(weeks=1):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return self.created_at.strftime('%Y-%m-%d')


class VoteSelect(models.Model):
    vote = models.ForeignKey(Vote, on_delete=models.CASCADE)
    select_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='selections')
    content = models.CharField(max_length=100)

groups/forms.py
from django import forms
from .models import Group, Post, PostImage, PostComment, Vote, VoteSelect
from imagekit.forms import ProcessedImageField


class GroupForm(forms.ModelForm):
    name = forms.CharField(label='그룹 이름', widget=forms.TextInput(
        attrs={'class': 'create-form',}))
    thumbnail = ProcessedImageField(
        required=True, widget=forms.ClearableFileInput(attrs={'class': 'create-form',}),
        label='그룹 프로필 이미지',
        label_suffix='',
        spec_id='image_size',
    )
    intro = forms.CharField(label='그룹 소개', widget=forms.Textarea(attrs={'class': 'create-form',}))
    
    class Meta:
        model = Group
        fields = ('name', 'thumbnail', 'intro',)


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # tailwind 클래스 추가
        self.fields["content"].label = ''
        self.fields["content"].widget.attrs['class'] = "block px-6 py-4 w-full text-lg text-gray-900 rounded-md border border-gray-300 focus:ring-[var(--color-main-light)] focus:border-[var(--color-main-light)]"
        self.fields["content"].widget.attrs['rows'] = "15"
        # self.fields["content"].widget.attrs['placeholder'] = '내용을 입력하세요'
        self.fields["title"].widget.attrs['class'] = "block py-2.5 px-1 mb-8 w-full text-2xl text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-[var(--color-main-light)] peer"
        self.fields["title"].widget.attrs['placeholder'] = '제목을 입력하세요'
        self.fields["title"].label = ''


    class Meta:
        model = Post
        fields = ('title', 'content',)


class PostImageDeleteForm(forms.ModelForm):
    delete_images = forms.ModelMultipleChoiceField(
        label = '삭제할 이미지 선택',
        queryset=PostImage.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
        required=False,
    )
    class Meta:
        model = PostImage
        fields = []

    # instance(post)의 이미지 참조
    def __init__(self, *args, **kwargs):
        instance = kwargs.pop('instance', None)
        super().__init__(*args, **kwargs)
        if instance:
            self.fields['delete_images'].queryset = instance.postimage_set.all()
    
    # 체크한 이미지가 담긴 cleaned_data['delete_images']에서 이미지 삭제
    def save(self, commit=True):
        for image in self.cleaned_data['delete_images']:
            image.delete()


class PostCommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["content"].widget.attrs["class"] = "block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-[var(--color-main-light)] focus:border-[var(--color-main-light)]"
        self.fields["content"].widget.attrs["placeholder"] = '댓글을 입력해주세요'
        self.fields["content"].widget.attrs["rows"] = 1
        self.fields["content"].label = ''


    class Meta:
        model = PostComment
        fields = ('content',)


class VoteForm(forms.ModelForm):
    title = forms.CharField(
        label='투표 제목',
        widget=forms.TextInput(
            attrs={
                'class': 'vote-form',
            }
        )
    )
    deadline = forms.DateTimeField(
        label='마감 기한',
        widget=forms.DateTimeInput(
            attrs={
                'type': 'datetime-local',
                'class': 'vote-form',
            }
        ),
    )
    is_overlap = forms.BooleanField(
        label='복수 선택',
        widget=forms.CheckboxInput(
            attrs={
                'class': 'vote-checkform',
            }
        ),
        required=False,
    )
    is_annony = forms.BooleanField(
        label='익명 투표',
        widget=forms.CheckboxInput(
            attrs={
                'class': 'vote-checkform',
            }
        ),
        required=False,
    )
    is_addible = forms.BooleanField(
        label='멤버의 선택지 추가 권한',
        widget=forms.CheckboxInput(
            attrs={
                'class': 'vote-checkform',
            }
        ),
        required=False,
    )
    class Meta:
        model = Vote
        fields = ('title', 'deadline', 'is_overlap', 'is_annony', 'is_addible',)

groups/templates/groups/group_setting.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ group }}{% endblock title %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/group_setting.css' %}">
{% endblock css %}

{% block side %}
  {% include 'sidebar.html' with current_group=group %}
{% endblock side %} 

{% block content %}



<div class="wrapper">
  <div class="content">
    <h1 class="title">그룹 관리</h1>

    <!-- 그룹 정보 -->
    <section>
      <h3 class="title">그룹 정보</h3>
      <div>
        <form class="space-y-6" action="{% url 'groups:group_update' group.pk %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="group-update">
            <p>{{ form.name.label }}</p>
            <div class="update-form">
              {{ form.name}}
            </div>
          </div>
          <div class="group-update file">
            <p>{{ form.thumbnail.label }}</p>
            <div class="flex flex-col">
              <div class="image group-img">
                <img src={{ group.thumbnail.url }} alt="그룹 이미지">
              </div>
              <div class="update-form">
                {{ form.thumbnail}}
              </div>
            </div>
          </div>
          <div class="group-update">
            <p>{{ form.intro.label }}</p>
            <div class="update-form">
              {{ form.intro}}
            </div>
          </div>
          <input type="submit" value="저장" class="main-btn bg-[var(--color-main)]">
        </form>
      </div>
    </section>

    <hr>

    <section>
      <h3 class="title">멤버 정보</h3>
      <ul class="user-list">
        <!-- 그룹 멤버 삭제, 방장 위임 -->
        {% for member in group.group_users.all %}
          <li class="user">
            <div class="info">
              <div class="user-img image">
                {% if member.image %}
                  <img src="{{ member.image.url }}" alt="멤버 프로필 사진">
                {% else %}
                  <img src="{% static 'img/blank_profile_img.png' %}" alt="멤버 프로필 사진">
                {% endif %}
              </div>
              <p>{{ member.nickname }}</p>
            </div>
            {% if member != request.user %}
              <div class="manage">
                <form action="{% url 'groups:chief_change' group.pk member.username %}" method="POST">
                  {% csrf_token %}
                  <input type="submit" value="방장 위임">
                </form>
                <form action="{% url 'groups:member_delete' group.pk member.username %}" method="POST">
                  {% csrf_token %}
                  <input type="submit" value="멤버 삭제" class="delete" onclick="return confirm('멤버를 삭제하시겠습니까?\n삭제한 멤버는 다시 초대할 수 있습니다.')">
                </form>
              </div>
            {% endif %}
          </li>
        {% endfor %}
      </ul>
    </section>

    <section class="flex justify-center">
      <div>
        <button data-modal-target="group-password-update-modal" data-modal-toggle="group-password-update-modal" class="main-btn update mr-6">암호 변경</button>
        <a href="{% url 'groups:group_delete' group.pk %}" class="main-btn delete" onclick="return confirm('삭제한 그룹은 복구할 수 없습니다.\n정말 삭제하시겠습니까?')">그룹 삭제</a>
      </div>
    </section>

  </div>
</div>


<!-- 그룹 암호변경 modal -->
<div id="group-password-update-modal" tabindex="-1" aria-hidden="true" class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
  <div class="relative w-full max-w-lg max-h-full">
    <!-- Modal content -->
    <div class="relative bg-white rounded-lg shadow">
      <!-- Modal header -->
      <div class="flex items-start justify-between p-4 border-b rounded-t">
        <h3 class="text-xl font-semibold text-gray-900">그룹 암호 변경</h3>
        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" data-modal-hide="group-password-update-modal">
          <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
          <span class="sr-only">Close modal</span>
      </button>
      </div>
      <!-- Modal body -->
      <div class="p-6">
        <form action="{% url 'groups:password_update' group.pk %}" method="POST">
          {% csrf_token %}
          <div>
            <label for="old-password">기존 암호</label>
            <input type="password" id="old-password" name="old-password" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-[var(--color-main-light)] focus:border-[var(--color-main-light)] block w-full mt-1 p-2.5">
          </div>
          <div class="mt-4">
            <label for="new-password1">새 암호</label>
            <input type="password" id="new-password1" name="new-password1" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-[var(--color-main-light)] focus:border-[var(--color-main-light)] block w-full mt-1 p-2.5">
          </div>
          <div class="mt-4">
            <label for="new-password2">새 암호 확인</label>
            <input type="password" id="new-password2" name="new-password2" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-[var(--color-main-light)] focus:border-[var(--color-main-light)] block w-full mt-1 p-2.5">
          </div>
          <input type="submit" value="변경" class="main-btn bg-[var(--color-main)] mt-4">
        </form>
      </div>
    </div>
  </div>
</div>

{% if messages %}
  {% for message in messages %}
    <script>alert('{{ message }}')</script>
  {% endfor %}
{% endif %}

{% endblock content %}

groups/templates/groups/index.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/index_calendar.css' %}" />
    {% comment %} <link rel="stylesheet" type="text/css" href="{% static 'css/index/__calendar.css' %}" /> {% endcomment %}
    {% comment %} <link rel="stylesheet" type="text/css" href="{% static 'css/index/testing.css' %}" />   {% endcomment %}
{% endblock css %}
{% block content %}

    {% include 'navbar.html' %}

    <div id="group-index">
        <div class="content-container">
            <div id="calendar-container" class="content-item">
                <div id="calendar-area" class="calendar-area item-wrapper">
                    <div id="filter-area" class="filter-area"></div>
                </div>
            </div>
            <div class="content-item">
                <div id="group-area" class="item-wrapper">{% include "groups/index/__groups.html" with groups=groups %}</div>
            </div>
        </div>
    </div>

    {% comment %} 그룹 생성 모달 {% endcomment %}
    {% include 'groups/index/__group_create_modal.html' %}
    {% if user.calendar %}
    <form id="dataset" data-user-calendar-id="{{ user.calendar.id }}" hidden> 숨겨진 dataset</form>
    {% endif %}

<!-- 그룹 생성 실패 시 alert -->
{% if messages %}
{% for message in messages %}
  <script>alert('{{ message }}')</script>
{% endfor %}
{% endif %}


{% endblock content %}

{% block script %}
<script src="{% static 'js/index.js' %}"></script>
<script src="{% static 'js/index_calendar.js' %}"></script>
{% endblock script %}

groups/templates/groups/post_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}JELLY | 글 작성{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/diary_create.css' %}">
<link rel="stylesheet" href="{% static 'css/post_create.css' %}">
{% endblock css %}

{% block side %}
  {% include 'sidebar.html' with current_group=group %}
{% endblock side %}


{% block content %}
<div class="wrapper">
  <div class="content">
    {% block form %}
      <form action="{% url 'groups:post_create' group.pk %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        <div>
          {{ field.label_tag }}
          {{ field }}
        </div>
        {% endfor %}
        <div class="btns">
          <input type="file" name="images" id="post-images" multiple required>
          <div class="flex gap-4">
            <input type="submit" value="작성" class="main-btn bg-[var(--color-main)]">
            <a href="{% url 'diaries:index' %}" class="main-btn back" onclick="return confirm('글쓰기를 종료하시겠습니까?\n작성 중인 글은 저장되지 않습니다. ')">취소</a>
          </div>
        </div>
      </form>
    {% endblock form %}
  </div>
</div>

{% if messages %}
  {% for message in messages %}
    <script>alert('{{ message }}')</script>
  {% endfor %}
{% endif %}

{% endblock content %}

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
{% endblock script %}

groups/templates/groups/post_update.html
{% extends 'groups/post_create.html' %}

{% block form %}
  <form action="{% url 'groups:post_update' group.pk post.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ post_form.as_p }}
    {{ image_delete_form.as_p }}
    <div class="btns">
      <input type="file" name="images" id="post-images" multiple>
      <div class="flex gap-4">
        <input type="submit" value="저장" class="main-btn bg-[var(--color-main)]">
        <a href="{% url 'groups:post_detail' group.pk post.pk %}" class="main-btn back" onclick="return confirm('글쓰기를 종료하시겠습니까?\n작성 중인 글은 저장되지 않습니다. ')">취소</a>
      </div>
    </div>
  </form>
</div>

{% if messages %}
  {% for message in messages %}
    <script>alert('{{ message }}')</script>
  {% endfor %}
{% endif %}

{% endblock form %}