accounts/urls.py
from django.urls import path, include
from . import views
from schedules.urls import user_schedule_router 

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<username>/', views.profile, name='profile'),
    path('profile/<username>/post/', views.profile, name='profile_share'),
    path('profile/<username>/share/', views.profile, name='profile_share'),
    path('profile/<username>/calendar/', views.profile, name='profile_share'),
    path('profile/<username>/calendar/schedules/', include(user_schedule_router.urls)),
]

chat/urls.py
# chat/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("<int:group_pk>/", views.group_chat, name="group_chat"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
import custom_ckeditor.views

from schedules.urls import user_schedule_router 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('accounts/', include('accounts.urls')),
    path('diaries/', include('diaries.urls')),
    path('groups/', include('groups.urls')),
    path('schedules/', include('schedules.urls')),
    path("chat/", include("chat.urls")),
    path("ckeditor5/image_upload/", custom_ckeditor.views.upload_file, name="ck_editor_5_upload_file"),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('accounts/', include('allauth.urls')),
    path('schedules/', include(user_schedule_router.urls)),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager as BaseUserManager
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail
from django.contrib.contenttypes import fields

# Create your models here.
class UserManager(BaseUserManager):
    def _create_user(self, username, email, password, **extra_fields):
        user = super()._create_user(username, email, password, **extra_fields)
        user._calendar.create()
        return user



class User(AbstractUser):
    nickname = models.CharField(max_length=20, default="젤리곰")
    #프로필 이미지 원본을 저장할지 논의
    image = ProcessedImageField(upload_to='users',
                                null=True,
                                blank=True,
                                processors=[Thumbnail(300,300)],
                                format='JPEG',
                                options={'quality': 80})
    """
    for calendar model
    """
    objects = UserManager()
    _calendar = fields.GenericRelation('schedules.Calendar', object_id_field='owner_object_id', content_type_field='owner_content_type', related_query_name='owner_user')
    
    @property
    def name(self):
        return f'{self.username}'
    @property 
    def calendar(self):
        return self._calendar.all()[0]
    @property
    def permitted_calendar_id(self):
        return [self.calendar.id, *(group.calendar.id for group in self.user_groups.all())]

    

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, UserCreationForm, UserChangeForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from django.forms.widgets import ClearableFileInput


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        label='',
        widget=forms.TextInput(
            attrs={
                'class': 'login-form-control',
                'placeholder': '사용자 ID',
            }
        )
    )
    password = forms.CharField(
        label='',
        widget=forms.PasswordInput(
            attrs={
                'class': 'login-form-control',
                'placeholder': '비밀번호',
            }
        )
    )


class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        label='사용자 ID',
        widget=forms.TextInput(
            attrs={
                'class': 'signup-form-control',
                'placeholder': '사용자 ID',
            }
        )
    )
    password1 = forms.CharField(
        label='비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'class': 'signup-form-control',
                'placeholder': '비밀번호',
            }
        )
    )
    password2 = forms.CharField(
        label='비밀번호 확인',
        widget=forms.PasswordInput(
            attrs={
                'class': 'signup-form-control',
                'placeholder': '비밀번호 확인',
            }
        )
    )
    nickname = forms.CharField(
        label='닉네임',
        widget=forms.TextInput(
            attrs={
                'class': 'signup-form-control',
                'placeholder': '닉네임',
            }
        )
    )
    email = forms.CharField(
        label='이메일',
        widget=forms.EmailInput(
            attrs={
                'class': 'signup-form-control',
                'placeholder': '이메일',
            }
        )
    )
    image = forms.ImageField(
        label='프로필 이미지',
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'signup-form-control',
                'placeholder': '프로필 이미지',
            },
        ),
        required=False,
    )


    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'nickname', 'email', 'image',)


class CustomClearableFileInput(ClearableFileInput):
    template_name = 'accounts/custom_clearable_file_input.html'


class CustomUserChangeForm(UserChangeForm):
    nickname = forms.CharField(
        label='닉네임',
        widget=forms.TextInput(
            attrs={
                'class': 'signup-form-control',
                'placeholder' : '닉네임',
            }
        )
    )
    email = forms.CharField(
        label='이메일',
        widget=forms.EmailInput(
            attrs={
                'class': 'signup-form-control',
                'placeholder' : '이메일',
            }
        )
    )
    image = forms.ImageField(
        label='프로필 이미지',
        widget= CustomClearableFileInput(
            attrs={
                'class': 'signup-form-control',
                'placeholder' : '프로필 이미지',
            },
        ),
        required=False,
    )

    password = None
    
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('nickname', 'email','image',)


class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label='기존 비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'class': 'signup-form-control',
                'placeholder' : '기존 비밀번호',
            },
        ),
    )
    new_password1= forms.CharField(
        label='새 비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'class': 'signup-form-control',
                'placeholder' : '새 비밀번호',
            },
        ),
    )
    new_password2 = forms.CharField(
        label='새 비밀번호 확인',
        widget=forms.PasswordInput(
            attrs={
                'class': 'signup-form-control',
                'placeholder' : '새 비밀번호 확인',
            },
        ),
    )   

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login, authenticate
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model, update_session_auth_hash
from .forms import CustomAuthenticationForm, CustomUserCreationForm, CustomUserChangeForm, CustomPasswordChangeForm
from diaries.models import Diary, DiaryShare
from django.core.paginator import Paginator
from schedules.models import Calendar


def login(request):
    if request.user.is_authenticated:
        return redirect('groups:index')

    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            next_url = request.POST.get('next')
            if next_url:
                return redirect(next_url)
        return redirect('groups:index')
    else:
        form = CustomAuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@login_required
def logout(request):
    auth_logout(request)
        
    return redirect('accounts:login')


def signup(request):
    if request.user.is_authenticated:
        return redirect('groups:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            user._calendar.create() # create calendar
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            auth_login(request, user)
            return redirect('groups:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('accounts:login')


@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            if 'image_clear' in request.POST:
                if request.user.image:
                    request.user.image.delete()
            form.save()
            return redirect('accounts:profile', request.user)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('accounts:profile', request.user)
    else:
        form = CustomPasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)


def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    diaries = Diary.objects.filter(user=person).order_by('-pk')
    shared_diaries = DiaryShare.objects.filter(diary__user=person).order_by('-pk')
    page= request.GET.get('page', '1')
    per_page = 5

    diaries_paginator = Paginator(diaries, per_page)
    shared_paginator = Paginator(shared_diaries, per_page)

    page_diaries = diaries_paginator.get_page(page)
    page_shared = shared_paginator.get_page(page)
    context = {
        'person': person,
        'diaries': page_diaries,
        'shared_diaries': page_shared,
    }
    return render(request, 'accounts/profile.html', context)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/accounts/login.css' %}"> 
{% endblock css %}


{% block content %}
<div class='update-container'>
  <div class='signup-box'>
    <div class='signup-logo'>
      <a href="{% url 'accounts:login' %}"><img src="{% static 'img/index_logo.png' %}" alt=""></a>
    </div>
    <form class='signup-form' action="{% url 'accounts:change_password' %}" method="POST">
      {% csrf_token %}
      {% for field in form %}
      <div>
        {{ field }}
      </div> 
      {% endfor %}
      <button class='change-password-btn'>비밀번호 변경</button>
    </form>
  </div>
</div>
{% endblock content %}

accounts/templates/accounts/custom_clearable_file_input.html
<span class="clearable-file-input">
  {% if widget.value.url %}
  <div class='flex mt-4'>
    <p style='color: rgb(84, 82, 82);'>기존 이미지를 삭제하시겠습니까?</p>
    <input style='border-radius: 3px; margin-left: 15px; margin-top: 3px; margin-right: 2px' type="checkbox" name="{{ widget.name }}_clear" id="id_{{ widget.name }}_clear">
    <label style='color: rgb(84, 82, 82);' for="id_{{ widget.name }}_clear">삭제</label>
  </div>
  {% else %}
  {% endif %}
  <p class='mt-3' style='color: rgb(84, 82, 82);'>새로운 프로필 이미지를 선택해 주세요</p>
  <input type="{{ widget.type }}" name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>
</span>

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/accounts/login.css' %}"> 
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css" integrity="sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock css %}



{% block content %}
<div style='background-color:#b4baee;'>
  <div class='login-container'>
    <div class="owl-carousel owl-theme">
      <div><img style='height: 55vh;' src="{% static 'img/login_intro/index.png' %}" alt=""></div>
      <div><img style='height: 55vh;' src="{% static 'img/login_intro/group_main.png' %}" alt=""></div>
      <div><img style='height: 55vh;' src="{% static 'img/login_intro/chat.png' %}" alt=""></div>
      <div><img style='height: 55vh;' src="{% static 'img/login_intro/diary_main.png' %}" alt=""></div>
      <div><img style='height: 55vh;' src="{% static 'img/login_intro/diary_detail.png' %}" alt=""></div>
    </div>
    <div class='login-box'>
      <div class='logo'><img src="{% static 'img/index_logo.png' %}" alt=""></div>
      <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {% for field in form  %}
        <div>
            {{ field }}
        </div>
        {% endfor %}
        {% if request.GET.next %}
          <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <button class='login-btn'>로그인</button>
      </form>
      <a class='login-btn' href="{% url 'accounts:signup' %}">회원가입</a>
      <div class='bar'></div>
      {% comment %} 소셜로그인 {% endcomment %}
      {% load socialaccount %}
      <a href="{% provider_login_url 'kakao' method='oauth2' %}" class="social--login">
        <img src="{% static 'img/kakao_login.png' %}" alt="">
      </a>
      <a href="{% provider_login_url 'google' method='oauth2' %}" class="social--login">
        <div class='social-box'>
          <img style='width: 2rem; margin: 10px' src="{% static 'img/google_logo.jpg' %}" alt="">
          <p style='margin-left: 20px'>구글 로그인</p>
        </div>
      </a> 
    </div>
  </div>
</div>

{% endblock content %}

{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js" integrity="sha512-pumBsjNRGGqkPzKHndZMaAG+bir374sORyzM3uulLV14lN5LyykqNk8eEeUlUkB3U0M4FApyaHraT65ihJhDpQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script type="text/javascript">
  $('.owl-carousel').owlCarousel({
      loop:false,
      margin:10,
      autoplay:true,           // 자동재생 여부
      autoplayTimeout:1800,    // 재생간격
      rewind: true,
      nav:false,
      responsive:{
          0:{
              items:1,
              slideBy:1,
              rows:1,
          },
          
      }
  })
</script>

{% comment %} <script type="text/javascript">
  $(document).ready(function(){
      var owl = $('.owl-carousel');
      
      owl.owlCarousel({
          items:3,                 // 한번에 보여줄 아이템 수
          loop:true,               // 반복여부
          margin:35,               // 오른쪽 간격
          autoplay:true,           // 자동재생 여부
          autoplayTimeout:1800,    // 재생간격
          autoplayHoverPause:true  //마우스오버시 멈출지 여부
      });    
      
      $('.customNextBtn').click(function() {
          owl.trigger('next.owl.carousel');
      })
      
      $('.customPrevBtn').click(function() {
          owl.trigger('prev.owl.carousel', [300]);
      })
  });
  </script> {% endcomment %}
{% endblock script %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/accounts/login.css' %}"> 
{% endblock css %}

{% block content %}
<div class='signup-container'>
  <div class='signup-box'>
    <div class='signup-logo'>
      <a href="{% url 'accounts:login' %}"><img src="{% static 'img/index_logo.png' %}" alt=""></a>
    </div>
    <form class='signup-form' action="{% url 'accounts:signup' %}" method="POST" enctype = 'multipart/form-data'>
      {% csrf_token %}
      {% for field in form %}
      <div>
        {{ field }}
      </div> 
      {% endfor %}
      <button class='signup-btn'>회원가입</button>
    </form>
  </div>
</div>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/accounts/login.css' %}"> 
{% endblock css %}

{% block content %}

<div class='update-container '>
  <div class='signup-box'>
    <div class='signup-logo'>
      <a href="{% url 'accounts:login' %}"><img src="{% static 'img/index_logo.png' %}" alt=""></a>
    </div>
    <form class='signup-form' action="{% url 'accounts:update' %}" method="POST" enctype = 'multipart/form-data'>
      {% csrf_token %}
     {% for field in form %}
        <div>
          {{ field }}
        </div>
      {% endfor %}
      <button class='update-btn'>정보수정</button> 
      <a class='change-password-btn' href="{% url 'accounts:change_password' %}">비밀번호 변경</a>
    </form>
  </div>
</div>

{% endblock content %}