accounts/urls.py
from django.urls import path, include
from . import views
from schedules.urls import user_schedule_router 

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<username>/', views.profile, name='profile'),
    path('profile/<username>/post/', views.profile, name='profile_share'),
    path('profile/<username>/share/', views.profile, name='profile_share'),
    path('profile/<username>/calendar/', views.profile, name='profile_share'),
    path('profile/<username>/calendar/schedules/', include(user_schedule_router.urls)),
]

chat/urls.py
# chat/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("<int:group_pk>/", views.group_chat, name="group_chat"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
import custom_ckeditor.views

from schedules.urls import user_schedule_router 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('accounts/', include('accounts.urls')),
    path('diaries/', include('diaries.urls')),
    path('groups/', include('groups.urls')),
    path('schedules/', include('schedules.urls')),
    path("chat/", include("chat.urls")),
    path("ckeditor5/image_upload/", custom_ckeditor.views.upload_file, name="ck_editor_5_upload_file"),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('accounts/', include('allauth.urls')),
    path('schedules/', include(user_schedule_router.urls)),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diaries/urls.py
from django.urls import path
from . import views

app_name = 'diaries'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:diary_pk>/', views.detail, name='detail'),
    path('<int:diary_pk>/update/', views.update, name='update'),
    path('<int:diary_pk>/delete/', views.delete, name='delete'),
    path('<int:group_pk>/<int:diary_pk>/', views.group_detail, name='group_detail'),
    path('<int:group_pk>/<int:diary_pk>/share/', views.share, name='share'),
    path('<int:group_pk>/<int:diary_pk>/unshare/', views.unshare, name='unshare'),
    path('<int:group_pk>/<int:diary_pk>/emotes/<int:emotion>/', views.emotes, name='emotes'),
    path('<int:group_pk>/<int:diary_pk>/comment_create/', views.comment_create, name='comment_create'),
    path('<int:group_pk>/<int:diary_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
    path('<int:group_pk>/<int:diary_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:group_pk>/<int:diary_pk>/comments/<int:comment_pk>/like/', views.comment_like, name='comment_like'),
]

groups/urls.py
from django.urls import path, include
from schedules.urls import group_schedule_router
from . import views

app_name = 'groups'
urlpatterns = [
    path('', views.index, name='index'),
    # 그룹
    path('create/', views.group_create, name='group_create'),
    path('<int:group_pk>/join/', views.group_join, name='group_join'),
    path('<int:group_pk>/', views.group_detail, name='group_detail'),
    path('<int:group_pk>/setting/', views.group_setting, name='group_setting'),
    path('<int:group_pk>/update/', views.group_update, name='group_update'),
    path('<int:group_pk>/delete/', views.group_delete, name='group_delete'),
    path('<int:group_pk>/password_update/', views.password_update, name='password_update'),
    path('<int:group_pk>/members/withdraw/', views.member_withdraw, name='member_withdraw'), # 멤버 탈퇴(본인이)
    path('<int:group_pk>/members/<str:username>/delete/', views.member_delete, name='member_delete'), # 멤버 삭제(방장 권한)
    path('<int:group_pk>/chief/<str:username>/change/', views.chief_change, name='chief_change'), # 방장 위임
    # 게시글
    path('<int:group_pk>/posts/create/', views.post_create, name='post_create'),
    path('<int:group_pk>/posts/<int:post_pk>/', views.post_detail, name='post_detail'),
    path('<int:group_pk>/posts/<int:post_pk>/update/', views.post_update, name='post_update'),
    path('<int:group_pk>/posts/<int:post_pk>/delete/', views.post_delete, name='post_delete'),
    path('<int:group_pk>/posts/<int:post_pk>/emotes/<int:emotion>/', views.emote, name='emote'),
    path('<int:group_pk>/posts/<int:post_pk>/comment/create/', views.comment_create, name='comment_create'),
    path('<int:group_pk>/posts/<int:post_pk>/comment/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
    path('<int:group_pk>/posts/<int:post_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:group_pk>/posts/<int:post_pk>/comments/<int:comment_pk>/like/', views.comment_like, name='comment_like'),
    path('<int:group_pk>/posts/<int:post_pk>/notice/', views.notice_post, name='notice_post'),
    # 투표
    path('<int:group_pk>/votes/create/', views.vote_create, name='vote_create'),
    path('votes/<int:vote_pk>/', views.get_vote, name='get_vote'),
    path('<int:group_pk>/votes/<int:vote_pk>/throw/', views.throw_vote, name='throw_vote'),
    path('<int:group_pk>/votes/<int:vote_pk>/add_option/', views.add_option, name='add_option'),
    path('<int:group_pk>/votes/<int:vote_pk>/update/', views.vote_update, name='vote_update'),
    path('<int:group_pk>/votes/<int:vote_pk>/delete/', views.vote_delete, name='vote_delete'),
    path('<int:group_pk>/votes/<int:vote_pk>/notice/', views.notice_vote, name='notice_vote'),
    path('votes/<int:vote_pk>/hits/', views.vote_hits, name='vote_hits'),
    path('search/', views.group_search, name='group_search'),
    path('<int:group_pk>/calendars/', include(group_schedule_router.urls)),
]

diaries/models.py
from django.db import models
from django.conf import settings
from django_ckeditor_5.fields import CKEditor5Field
from datetime import datetime, timedelta
from django.utils import timezone
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail
from urllib.parse import urljoin


# Create your models here.
class Diary(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = CKEditor5Field('Content', config_name='extends')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    share = models.ManyToManyField('groups.Group', related_name='group_diaries', verbose_name='shared diary to group', through='DiaryShare')
    hit = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='diary_views')
    thumbnail =  models.CharField(max_length=500, blank=True)

    def __str__(self):
        return self.title

    def increase_hit(self, user):
        diary_share, created = DiaryShare.objects.get_or_create(diary=self)

        if user not in diary_share.hit.all():
            diary_share.hit.add(user)

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.created_at
        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(time.seconds // 60) + '분 전'
        elif time < timedelta(days=1):
            return str(time.seconds // 3600) + '시간 전'
        elif time < timedelta(weeks=1):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return self.created_at.strftime('%Y-%m-%d')


class DiaryShare(models.Model):
    diary = models.ForeignKey(Diary, on_delete=models.CASCADE)
    group = models.ForeignKey('groups.Group', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_model_name(self):
        return self._meta.model_name

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.created_at
        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(time.seconds // 60) + '분 전'
        elif time < timedelta(days=1):
            return str(time.seconds // 3600) + '시간 전'
        elif time < timedelta(weeks=1):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return self.created_at.strftime('%Y-%m-%d')


class DiaryComment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comments')
    share = models.ForeignKey(DiaryShare, on_delete=models.CASCADE)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_diarycomments')
    
    class Meta:
         ordering = ['created_at']


class DiaryEmote(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='emotions')
    share = models.ForeignKey(DiaryShare, on_delete=models.CASCADE)
    emotion = models.PositiveIntegerField()
    class Meta:
        unique_together = [['user', 'share']]
    # 1:👍 2:🥰 3:🤣 4:😲 5:😭 6:🥳

diaries/forms.py
from django import forms
from .models import Diary, DiaryComment

class DiaryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["content"].required = False
        # tailwind 클래스 추가
        self.fields["content"].label = ''
        self.fields["title"].widget.attrs['class'] = "block py-2.5 px-1 mb-8 w-full text-2xl text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-[var(--color-main-light)] peer"
        self.fields["title"].widget.attrs['placeholder'] = '제목을 입력하세요'
        self.fields["title"].label = ''
        self.fields["thumbnail"].label = ''

        
    class Meta:
        model = Diary
        fields = '__all__'
        exclude = ('user', 'share', 'hit',)
        widgets = {
            'thumbnail': forms.HiddenInput(
                attrs={
                    'id': 'thumbnail_input',
                }
            ),
        }


class DiaryCommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["comment"].widget.attrs["class"] = "block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-[var(--color-main-light)] focus:border-[var(--color-main-light)]"
        self.fields["comment"].widget.attrs["placeholder"] = '댓글을 입력해주세요'
        self.fields["comment"].widget.attrs["rows"] = 1
        self.fields["comment"].label = ''


    class Meta:
        model = DiaryComment
        fields = ('comment',)

diaries/templates/diaries/create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}JELLY | 글 작성{% endblock title %}

{% block css %}
{% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous"> {% endcomment %}
<link rel="stylesheet" href="{% static 'css/diary_create.css' %}">
{% endblock css %}

{% block side %}
  {% include 'sidebar.html' with current_group=group %}
{% endblock side %}


{% block content %}
<div class="wrapper">
  <div class="content">
    <div class="hidden absolute inline-flex items-center justify-center w-6 h-6 text-xs font-bold text-white rounded-full -top-2 -right-2 dark:border-gray-900" id="check">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#F05252" class="w-6 h-6">
        <path fill-rule="evenodd" d="M2.25 12c0-5.385 4.365-9.75 9.75-9.75s9.75 4.365 9.75 9.75-4.365 9.75-9.75 9.75S2.25 17.385 2.25 12zm13.36-1.814a.75.75 0 10-1.22-.872l-3.236 4.53L9.53 12.22a.75.75 0 00-1.06 1.06l2.25 2.25a.75.75 0 001.14-.094l3.75-5.25z" clip-rule="evenodd" />
      </svg>      
    </div>
    <form action="{% block url %}{% url 'diaries:create' %}{% endblock url %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.media }}
      {% for field in form %}
      <div>
        {{ field.label_tag }}
        {{ field }}
      </div>
      {% endfor %}
      <div class="btns">
        <div id="select-thumbnail-btn" class="main-btn select">썸네일 선택하기</div>
        <div class="flex gap-4">
          <input type="submit" value="작성" class="main-btn bg-[var(--color-main)]">
          <a href="{% url 'accounts:profile' user.username %}" class="main-btn back" onclick="return confirm('글쓰기를 종료하시겠습니까?\n작성 중인 글은 저장되지 않습니다. ')">취소</a>
        </div>
      </div>
    </form>
  </div>
</div>

<div class="thumbnail-btn">
  <span>썸네일</span>
</div>
{% endblock content %}

{% block error %}
{% endblock error %}

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
<script src="{% static 'js/diary_create.js' %}"></script>
{% endblock script %}

diaries/templates/diaries/group_detail.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'css/diary.css' %}">{% endblock css %}

{% block title %}JELLY | {{ diary.title }}{% endblock title %}

{% block side %}
  {% include 'sidebar.html' with current_group=group %}
{% endblock side %}

{% block content %}
<div class="wrapper">
  <div class="content">
    <section class="header justify-between">
      <div class="flex gap-2">
        <a href="{% url 'accounts:profile' user %}" class="diary main-btn">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-10 h-10">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
          </svg>          
        </a>
        {% comment %} <a href="{% url 'diaries:index' %}" class="diary main-btn">이전글</a>
        <a href="{% url 'diaries:index' %}" class="diary main-btn">다음글</a> {% endcomment %}
      </div>
    </section>

    <section class="post-content">
      <div class="flex flex-col px-2">
        <div class="flex items-center">
          <h2 class="title">{{ diary.title }}</h2>
          {% if request.user == diary.user %}
            <button id="postManageDropdownButton" data-dropdown-toggle="postManageDropdown" type="button">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#9d9c9c" class="w-8 h-8">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM12.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM18.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0z" />
              </svg>
            </button>
            <!-- Dropdown menu -->
            <div id="postManageDropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44">
                <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="postManageDropdownButton">
                  <li class="hover:bg-gray-100">
                    <form action="{% url 'diaries:unshare' group.pk diary.pk %}">
                      {% csrf_token %}
                      <input type="submit" value="공유취소" class="diary px-4 py-2" onclick="return confirm('해당 게시글에 포함된 댓글도 함께 삭제됩니다.\n공유를 취소하시겠습니까?')">
                    </form>
                  </li>
                  <li class="hover:bg-gray-100">
                    <a href="{% url 'diaries:update' diary.pk %}" class="block diary px-4 py-2">수정</a>
                  </li>
                  <!--
                  <li class="hover:bg-gray-100">
                    <a href="{% url 'groups:notice_post' group.pk diary.pk %}" class="block diary px-4 py-2">공지 등록</a>
                  </li>-->
                  <li class="hover:bg-gray-100">
                    <a href="{% url 'diaries:delete' diary.pk %}" class="block diary delete px-4 py-2" onclick="return confirm('정말 삭제하시겠습니까?')">삭제</a>
                  </li>
                </ul>
            </div>
          {% endif %}
        </div>
        <div class="flex justify-between items-end">
          <div class="flex items-center">
            <div class="create-user-img w-10 h-10 mr-2">
              {% if diary.user.image %}
                <img src="{{ diary.user.image.url }}" alt="">
              {% else %}
                <img src="{% static 'img/blank_profile_img.png' %}" alt="">
              {% endif %}
            </div>
            <div class="flex-grow">
              <p>{{ diary.user.nickname }}</p>
              <div class="flex gap-2">
                <p class="date">{{ diary.created_at }}</p>
                <p class="date">조회 {{ diary.hit.all|length }}</p>
              </div>
            </div>
          </div>
          <div class="scroll">
            <div class="reaction-item">
              <svg xmlns="http://www.w3.org/2000/svg" fill="var(--color-main)" viewBox="0 0 24 24" stroke-width="1.5" stroke="var(--color-main)" class="w-5 h-5">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 20.25c4.97 0 9-3.694 9-8.25s-4.03-8.25-9-8.25S3 7.444 3 12c0 2.104.859 4.023 2.273 5.48.432.447.74 1.04.586 1.641a4.483 4.483 0 01-.923 1.785A5.969 5.969 0 006 21c1.282 0 2.47-.402 3.445-1.087.81.22 1.668.337 2.555.337z" />
              </svg>
              <p>{{ comments|length }}</p>
            </div>
            <div class="reaction-item">
              <svg xmlns="http://www.w3.org/2000/svg" fill="var(--color-main)" viewBox="0 0 24 24" stroke="var(--color-main)" stroke="currentColor" class="w-5 h-5">
                <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
              </svg>
              <p>{{ diary_share.diaryemote_set.all|length }}</p>
            </div>
          </div>
        </div>

      </div>
      <hr class="diary-hr">
      <div class="ck-content diary-detail">
        {{ diary.content|safe }}
      </div>
      <div class="relative">
        <a href="#" class="top-btn">
          <svg style="color: rgb(0, 0, 0);" xmlns="http://www.w3.org/2000/svg" width="6" height="6" fill="currentColor" class="bi bi-triangle-fill" viewBox="0 0 16 16"> <path fill-rule="evenodd" d="M7.022 1.566a1.13 1.13 0 0 1 1.96 0l6.857 11.667c.457.778-.092 1.767-.98 1.767H1.144c-.889 0-1.437-.99-.98-1.767L7.022 1.566z" fill="#000000"></path> </svg>
          TOP
        </a>
      </div>
      </section>
      {% comment %} 1:👍 2:🥰 3:🤣 4:😲 5:😭 6:🥳 {% endcomment %}
      <div class="post-content bottom">
        <section class="reaction">
          <div>
            <button id="dropdownRightButton" data-dropdown-toggle="dropdownRight" data-dropdown-placement="right" class="diary reaction-count" type="button">
              <svg xmlns="http://www.w3.org/2000/svg" fill="#FACA1590" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15.182 15.182a4.5 4.5 0 01-6.364 0M21 12a9 9 0 11-18 0 9 9 0 0118 0zM9.75 9.75c0 .414-.168.75-.375.75S9 10.164 9 9.75 9.168 9 9.375 9s.375.336.375.75zm-.375 0h.008v.015h-.008V9.75zm5.625 0c0 .414-.168.75-.375.75s-.375-.336-.375-.75.168-.75.375-.75.375.336.375.75zm-.375 0h.008v.015h-.008V9.75z" />
              </svg>
              <p class="emotion-total-count">{{ diary_share.diaryemote_set.all|length }}</p>
            </button>
            {% comment %} 감정표현 드랍다운 메뉴 {% endcomment %}
            <div id="dropdownRight" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow">
              <ul class="emotion-group" aria-labelledby="dropdownDefaultButton">
                {% for emotion in emotions %}
                  <li class="emotion {% if emotion.exist %}selected-emotion{% endif %}">
                    {% if request.user.is_authenticated %}
                      {{ emotion.queryset }}
                      <form class="emotion-form" data-group-id="{{ group.pk }}" data-diary-id="{{ diary.pk }}" data-emotion="{{ emotion.value }}">
                        {% csrf_token %}
                        <button class="emotion-btn">
                          {% if emotion.value == 1 %}
                            <span class="emotion-emoji">👍</span>
                          {% elif emotion.value == 2 %}
                            <span class="emotion-emoji">🥰</span>
                          {% elif emotion.value == 3 %}
                            <span class="emotion-emoji">🤣</span>
                          {% elif emotion.value == 4 %}
                            <span class="emotion-emoji">😲</span>
                          {% elif emotion.value == 5 %}
                            <span class="emotion-emoji">😭</span>
                          {% else %}
                            <span class="emotion-emoji">🥳</span>
                          {% endif %}
                          <span>{{emotion.label}}</span>
                          <p class="emotion-count">{{ emotion.count }}</p>
                        </button>
                      </form>
                    {% else %}
                    {% endif %}
                  </li>
                {% endfor %}
              </ul>
            </div>
          </div>
          <div class="reaction-count">
            <span>댓글</span>
            <span>{{ comments|length }}</span>
          </div>
        </section>

        <section>
          <div>
            {% comment %} 댓글 작성 칸 {% endcomment %}
            <form action="{% url 'diaries:comment_create' group.pk diary.pk %}" method="POST" class="comment-form">
              {% csrf_token %}
              {{ comment_form }}
              <input type="submit" value="작성" class="comment main-btn">
            </form>
          </div>
          {% comment %} 댓글 리스트 {% endcomment %}
          <div class="comment-wrapper">
            {% if comments %}
              {% for comment in comments %}
                <div class="comment-area" data-comment-id="{{ comment.pk }}" data-group-id="{{ group.pk }}" data-diary-id="{{ diary.pk }}">
                  <div class="user-img image">
                  </div>
                  <div class="comment-content">
                    <div class="flex gap-3">
                      <div class="create-user-img">
                        {% if comment.user.image %}
                          <img src="{{ comment.user.image.url }}" alt="">
                        {% else %}
                          <img src="{% static 'img/blank_profile_img.png' %}" alt="">
                        {% endif %}
                      </div>
                      <div class="grow">
                        <p class="comment-user">{{ comment.user.nickname }}</p>
                        <p class="comment-comment">{{ comment.comment }}</p>
                        <form id="comment-update-form" class="hidden comment-form">
                          {% csrf_token %}
                          {{ comment_form }}
                          <input type="submit" value="수정" class="comment main-btn">
                        </form>
                        <div class="date comment-bottom">
                          <div class="comment-bottom-item">
                            <p>{{ comment.created_at }}</p>
                            <form class="comment-like-form">
                              {% csrf_token %}
                              <button type="submit" class="comment-like-btn">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="{% if request.user in comment.like_users.all %}#E02424{% else %}none{% endif %}" viewBox="0 0 24 24" stroke-width="1.5" stroke="#E02424" class="w-4 h-4">
                                  <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
                                </svg>
                                <span>{{ comment.like_users.count }}</span>
                              </button>
                            </form>
                          </div>
                          <div class="comment-bottom-item">
                            {% if comment.user == request.user %}
                              <button class="comment-update-btn">댓글 수정</button>
                              <form action="{% url 'diaries:comment_delete' group.pk diary.pk comment.pk %}" method="POST">
                                {% csrf_token %}
                                <input type="submit" value="댓글삭제" class="delete" onclick="return confirm('댓글을 삭제하시겠습니까?')">
                              </form>
                            {% endif %}
                          </div>
                        </div>
                      </div>
                    </div>
                    
                  </div>
                </div>
                <hr class="comment-hr">
              {% endfor %}
            {% else %}
              <div class="no-comment">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1" stroke="currentColor" class="w-12 h-12">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 12a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375M21 12c0 4.556-4.03 8.25-9 8.25a9.764 9.764 0 01-2.555-.337A5.972 5.972 0 015.41 20.97a5.969 5.969 0 01-.474-.065 4.48 4.48 0 00.978-2.025c.09-.457-.133-.901-.467-1.226C3.93 16.178 3 14.189 3 12c0-4.556 4.03-8.25 9-8.25s9 3.694 9 8.25z" />
                </svg>
                <h3>작성된 댓글이 없습니다.</h3>
              </div>
            {% endif %}
          </div>
        </section>
      </div>
  </div>
</div>
{% endblock content %}

{% block script %}
<script src="{% static 'js/diary_group.js' %}"></script>
{% endblock script %}

diaries/templates/diaries/update.html
{% extends 'diaries/create.html' %}

{% block title %}JELLY | {{ diary.title }}{% endblock title %}

{% block url %}
{% url 'diaries:update' diary.pk %}
{% endblock url %}

{% block error %}
{% if messages %}
  {% for message in messages %}
    <script>alert('{{ message }}')</script>
  {% endfor %}
{% endif %}
{% endblock error %}