accounts/urls.py
from django.urls import path, include
from . import views
from schedules.urls import user_schedule_router 

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<username>/', views.profile, name='profile'),
    path('profile/<username>/post/', views.profile, name='profile_share'),
    path('profile/<username>/share/', views.profile, name='profile_share'),
    path('profile/<username>/calendar/', views.profile, name='profile_share'),
    path('profile/<username>/calendar/schedules/', include(user_schedule_router.urls)),
]

chat/urls.py
# chat/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("<int:group_pk>/", views.group_chat, name="group_chat"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
import custom_ckeditor.views

from schedules.urls import user_schedule_router 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('accounts/', include('accounts.urls')),
    path('diaries/', include('diaries.urls')),
    path('groups/', include('groups.urls')),
    path('schedules/', include('schedules.urls')),
    path("chat/", include("chat.urls")),
    path("ckeditor5/image_upload/", custom_ckeditor.views.upload_file, name="ck_editor_5_upload_file"),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('accounts/', include('allauth.urls')),
    path('schedules/', include(user_schedule_router.urls)),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groups/urls.py
from django.urls import path, include
from schedules.urls import group_schedule_router
from . import views

app_name = 'groups'
urlpatterns = [
    path('', views.index, name='index'),
    # 그룹
    path('create/', views.group_create, name='group_create'),
    path('<int:group_pk>/join/', views.group_join, name='group_join'),
    path('<int:group_pk>/', views.group_detail, name='group_detail'),
    path('<int:group_pk>/setting/', views.group_setting, name='group_setting'),
    path('<int:group_pk>/update/', views.group_update, name='group_update'),
    path('<int:group_pk>/delete/', views.group_delete, name='group_delete'),
    path('<int:group_pk>/password_update/', views.password_update, name='password_update'),
    path('<int:group_pk>/members/withdraw/', views.member_withdraw, name='member_withdraw'), # 멤버 탈퇴(본인이)
    path('<int:group_pk>/members/<str:username>/delete/', views.member_delete, name='member_delete'), # 멤버 삭제(방장 권한)
    path('<int:group_pk>/chief/<str:username>/change/', views.chief_change, name='chief_change'), # 방장 위임
    # 게시글
    path('<int:group_pk>/posts/create/', views.post_create, name='post_create'),
    path('<int:group_pk>/posts/<int:post_pk>/', views.post_detail, name='post_detail'),
    path('<int:group_pk>/posts/<int:post_pk>/update/', views.post_update, name='post_update'),
    path('<int:group_pk>/posts/<int:post_pk>/delete/', views.post_delete, name='post_delete'),
    path('<int:group_pk>/posts/<int:post_pk>/emotes/<int:emotion>/', views.emote, name='emote'),
    path('<int:group_pk>/posts/<int:post_pk>/comment/create/', views.comment_create, name='comment_create'),
    path('<int:group_pk>/posts/<int:post_pk>/comment/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
    path('<int:group_pk>/posts/<int:post_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:group_pk>/posts/<int:post_pk>/comments/<int:comment_pk>/like/', views.comment_like, name='comment_like'),
    path('<int:group_pk>/posts/<int:post_pk>/notice/', views.notice_post, name='notice_post'),
    # 투표
    path('<int:group_pk>/votes/create/', views.vote_create, name='vote_create'),
    path('votes/<int:vote_pk>/', views.get_vote, name='get_vote'),
    path('<int:group_pk>/votes/<int:vote_pk>/throw/', views.throw_vote, name='throw_vote'),
    path('<int:group_pk>/votes/<int:vote_pk>/add_option/', views.add_option, name='add_option'),
    path('<int:group_pk>/votes/<int:vote_pk>/update/', views.vote_update, name='vote_update'),
    path('<int:group_pk>/votes/<int:vote_pk>/delete/', views.vote_delete, name='vote_delete'),
    path('<int:group_pk>/votes/<int:vote_pk>/notice/', views.notice_vote, name='notice_vote'),
    path('votes/<int:vote_pk>/hits/', views.vote_hits, name='vote_hits'),
    path('search/', views.group_search, name='group_search'),
    path('<int:group_pk>/calendars/', include(group_schedule_router.urls)),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}JELLY{% endblock title %}</title>
  <script src="https://cdn.tailwindcss.com"></script>
  {% comment %} <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css" rel="stylesheet" /> {% endcomment %}
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <link rel="stylesheet" href="{% static 'css/flowbite.css' %}">
  <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
  <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
  {% block css %}{% endblock css %}
</head>
<body>
  {% comment %} 
    네브바가 필요한 템플릿에서는
    {% block navbar %}
      {% include 'navbar.html' %}
    {% endblock navbar %}
    추가해주시고 필요 없는 템플릿에서는 blcok 없이 작성해주시면 됩니다
    사이드바도 똑같습니다! 
    혹시 더 효율적인 방법을 알고 계시다면 말씀해주세요
  {% endcomment %}
  {% block navbar %}
  {% endblock navbar %}

  {% block side %}
  {% endblock side %}

  <main>
    {% block content %}
    {% endblock content %}
  </main>

  <footer class="bg-white">
    <div class="footer-wrapper">
      <hr class="mb-4 border-gray-200 sm:mx-auto" />
      <div class="w-full mx-auto max-w-screen-xl pt-2 flex flex-col items-center justify-between gap-4">
        <ul class="flex flex-wrap items-center mt-3 text-sm font-medium text-gray-500 sm:mt-0">
          <li>
            <a href="https://github.com/hyoung0" class="flex gap-2 items-center mr-4 hover:underline md:mr-8">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
              </svg>
              <span>hyoung0</span>
            </a>
          </li>
          <li>
            <a href="https://github.com/ruby04-dev" class="flex gap-2 items-center mr-4 hover:underline md:mr-8">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
              </svg>
              <span>LEE, SOOJUNG</span>
            </a>
          </li>
          <li>
            <a href="https://github.com/shunny822" class="flex gap-2 items-center mr-4 hover:underline md:mr-8">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
              </svg>
              <span>Suhyun Choe</span>
            </a>
          </li>
          <li>
            <a href="https://github.com/rloldl-c" class="flex gap-2 items-center mr-4 hover:underline md:mr-8">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
              </svg>
              <span>eunbi</span>
            </a>
          </li>
          <li>
            <a href="https://github.com/EnochSB" class="flex gap-2 items-center hover:underline">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
              </svg>
              <span>EnochSB</span>
            </a>
          </li>
        </ul>
        <span class="text-sm text-gray-500 sm:text-center">© 2023 <a href="https://github.com/JELLY-PJT/jelly" class="hover:underline">JELLY</a>. All Rights Reserved.</span>
      </div>
    </div>
  </footer>

  
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
{% block script %}
{% endblock script %}
</html>

templates/navbar.html
{% load static %}
<nav>
  <div class="row">
    <img src="{% static 'img/index_logo.png' %}" alt="로고" class="logo">
    {% if user.is_authenticated %}
      <div class="row nav--tab">
        <a href="{% url 'accounts:profile' user.username %}">
          <p>프로필</p>
        </a>
        <form action="{% url 'accounts:logout' %}" method='POST'>
          {% csrf_token %}
          <div class='nav-link'>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="rgb(84, 82, 82)" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15m3 0l3-3m0 0l-3-3m3 3H9" />
            </svg>
            <input type="submit" value='로그아웃'>
          </div>
        </form> 
      </div>
    {% else %}     
    {% endif %}
  </div>
  <div class="nav--line"></div> 
</nav>

templates/sidebar.html
{% load static %}
{% block css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/sidebar.css' %}">  
{% endblock css %}

<aside class="aside">
  <a href="{% url 'groups:index' %}">
    <img src="{% static 'img/side_logo.png' %}" alt="로고" class="side-logo">
  </a>
  {% if user.image %}
  <a href="{% url 'accounts:profile' user.username %}">
    <img src="{{ user.image.url}}" alt="프로필" class='side-img'>
  </a>
  {% else %}
  <a href="{% url 'accounts:profile' user.username %}">
    <img src="{% static 'img/blank_profile_img.png' %}" alt="기본 프로필 이미지" class='side-img'>
  </a>
    {% endif %}
  <div class='bar'></div>
  {% for group in request.user.user_groups.all %}
    {% if group == current_group %}
    {# 현재 접속 중인 그룹 - 클래스 수정 해 주세요 #}
    <a href="{% url 'groups:group_detail' group.pk %}">
      <img src="{{ group.thumbnail.url }}" alt="그룹이미지" class='side-img-border-color'>
    </a>
    {% else %}
    {# 나머지 그룹 #}
    <a href="{% url 'groups:group_detail' group.pk %}">
      <img src="{{ group.thumbnail.url }}" alt="그룹이미지" class='side-img'>
    </a>
    {% endif %}
  {% endfor %}
  <div class="bar"></div>
  {% comment %} 그룹 생성 모달 달아야함 {% endcomment %}
  <!-- Modal toggle -->
  <div class='flex flex-col justify-between grow'>
    <button data-modal-target="GroupCreate-modal" data-modal-toggle="GroupCreate-modal" class="GroupCreate-ModalToggle-btn" type="button">
      <img src="{% static 'img/side_PlusButton.png' %}" alt="그룹생성버튼" class='side-img side-plus'>
    </button>
    <form action="{% url 'accounts:logout' %}" method='POST'>
      {% csrf_token %}
      <div class='side-logout'>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="rgb(84, 82, 82)" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15m3 0l3-3m0 0l-3-3m3 3H9" />
        </svg>
        <input type="submit" value='로그아웃'>
      </div>
    </form>

  </div>
</aside>

<!-- Main modal -->
<div id="GroupCreate-modal" tabindex="-1" aria-hidden="true" class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
  <div class="relative w-full max-w-md max-h-full">
    <!-- Modal content -->
    <div class="relative GroupCreate-modal-content bg-white rounded-lg shadow">
      <button type="button" class="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" data-modal-hide="GroupCreate-modal">
        <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        <span class="sr-only">Close modal</span>
      </button>
      <div class="px-6 py-6 lg:px-8">
        <h3 class="mb-4 text-xl font-medium GroupCreate-txt">그룹을 만들어보세요</h3>
        <form action="{% url 'groups:group_create' %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <p class='Group-label'>{{ group_form.name.label }}</p>
          <p>{{ group_form.name }}</p>
          <p class='Group-label'>{{ group_form.intro.label }}</p>
          <p>{{ group_form.intro }}</p>
          <p class='Group-label'>{{ group_form.thumbnail.label }}</p>
          <p>{{ group_form.thumbnail}}</p>
          <!-- 그룹 비밀번호 -->
          <p class='Group-label'>그룹 암호</p>
          <p><input type="password" class="create-form" name="password1" required></p>
          <p class='Group-label'>그룹 암호 확인</p>
          <p><input type="password" class="create-form" name="password2" required></p>
          <button class='GroupCreate-btn'>그룹생성</button>
        </form>
      </div>
    </div>
  </div>
</div> 